plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.14.0'
}

group = 'ru.jafix'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-liquibase'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
	implementation 'org.openapitools:openapi-generator-gradle-plugin:7.14.0'

	implementation 'org.postgresql:postgresql:42.7.11'

	implementation 'org.mapstruct:mapstruct:1.6.3'
	implementation 'org.mapstruct:mapstruct-processor:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

openApiGenerate {
	generatorName = "java"

	inputSpec = "$rootDir/yookassa-openapi-specification.yaml"

	outputDir = "$buildDir/generated"

	apiPackage = "ru.jafix.client.api"
	modelPackage = "ru.jafix.client.model"
	invokerPackage = "ru.jafix.client.invoker"
}

openApiValidate {
	inputSpec = "$rootDir/api-docs.json"
}

tasks.named('test') {
	useJUnitPlatform()
}
