spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  application:
    name: task-application
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
  liquibase:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  expiration: 1800000
  key: 0JTQtdGA0LXQstC90Y8sINCz0LTQtSDRgdC60YPRh9Cw0Lsg0JXQstCz0LXQvdC40LksCtCR0YvQu9CwINC/0YC80YfQuNCy0YvRhSDQtNGA0LjQsNC0Lgo

server:
  port: 8080